// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiG0xMB9pPbeHsZoiZPg8to7E2fyNAgGA',
    appId: '1:816834019218:web:08b5b91b997756c6918b4b',
    messagingSenderId: '816834019218',
    projectId: 'paygofit-7cded',
    authDomain: 'paygofit-7cded.firebaseapp.com',
    storageBucket: 'paygofit-7cded.appspot.com',
    measurementId: 'G-5JJH3DJM9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSJdOGSBWrGHGDK5uvpWO6vWJooIHs78',
    appId: '1:816834019218:android:4c99b2a1d441ff65918b4b',
    messagingSenderId: '816834019218',
    projectId: 'paygofit-7cded',
    storageBucket: 'paygofit-7cded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuCOoC52xIe63n0l4mC_EAjJDlL_4R88',
    appId: '1:816834019218:ios:7a0a2f43728c7d3b918b4b',
    messagingSenderId: '816834019218',
    projectId: 'paygofit-7cded',
    storageBucket: 'paygofit-7cded.appspot.com',
    iosBundleId: 'com.example.progoFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuCOoC52xIe63n0l4mC_EAjJDlL_4R88',
    appId: '1:816834019218:ios:7a0a2f43728c7d3b918b4b',
    messagingSenderId: '816834019218',
    projectId: 'paygofit-7cded',
    storageBucket: 'paygofit-7cded.appspot.com',
    iosBundleId: 'com.example.progoFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiG0xMB9pPbeHsZoiZPg8to7E2fyNAgGA',
    appId: '1:816834019218:web:44ae3c636fd0139a918b4b',
    messagingSenderId: '816834019218',
    projectId: 'paygofit-7cded',
    authDomain: 'paygofit-7cded.firebaseapp.com',
    storageBucket: 'paygofit-7cded.appspot.com',
    measurementId: 'G-KFZQ8PPT0Q',
  );

}